### ISSUE TITLE
Make groupBy() a streamed operation, instead of returning Map

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOL#105]
The current implementation of `groupBy()` follows `Stream.collect()` in being a terminal operation. That's nonesense, of course. The operation should return a `Stream` of grouped objects, similar to `distinct()`, and `sorted()`, which are also not terminal operations.

**Comment by tkroman** [comment]
Should the result be something like `Seq<Tuple2<R, Seq<T>>` or should the implementation exclude classification keys? I'm tinkering around this issue and it's kinda hard to have a whole picture in mind without the specification :)

**Comment by lukaseder** [comment]
Yes that's the kind of result type that I had in mind. The implementation would need to maintain a buffer for each group, populating the group's sequence every time either the outer or the inner sequences are consumed.

**Comment by tkroman** [comment]
Hey @lukaseder , I wrote something in spirit of your Seq#partition method, except in this case we keep a Map of buffers since it is to be updated dynamically according to new partition keys' values (unlike in a simpler true/false case). Hence the clumsiness of this local class style. Perhaps you could review my commit from in general (I haven't pushed tests yet) and if you approve, I'd like to move at least outer local class to a static one, if that's OK.

**Comment by lukaseder** [comment]
Interesting implementation. I have a couple of concerns:

- We cannot further overload the `groupBy()` method, especially when lambda expressions should be passed as arguments, or we'll risk having ambiguities at the call-site.
- The `ClassifyingIterator.fetch()` method probably isn't optimal. I feel we shouldn't traverse `classes` every time we call `fetch()`, unless I'm missing something?
- `classes` should probably be a `LinkedHashMap` to preserve ordering

**Comment by tkroman** [comment]
Yep. I have exactly the same problems with current implementation. While I've already resolved 2nd and 3d points in my local branch, the ambiguity issue is something I'm still thinking on. Do you have any suggestions? I though, maybe `seq.grouping[By]()` will be OK? My first choice would be simply `grouped`, since it reflects the non-terminality of the operation, but Scala's `grouped` works totally different and that might be confusing for those who are familiar with both languages.

**Comment by lukaseder** [comment]
I like the `grouped()` proposal as it matches the existing `sorted()`. Also, we can establish that all methods ending in `By()` are terminal operations (e.g. `minBy()` and `maxBy()`).

We don't have to be very similar to Scala. The idea of `Seq` is to be a sequential Java `Stream`. There is already different wording, such as `limit()` instead of `take()`. `Seq` mimicks that wording by adding `limitWhile()` and `limitUntil()`

Besides, Scala's notion of `grouped()` is just as confusing. I wouldn't expect that behaviour under that name. I'd have called Scala's method `chunked()` or something like that.

**Comment by tkroman** [comment]
I've pushed some commits addressing those issues (a couple of tests included). Should I make a pull-request or is there anything else?

P.S. While running tests, I also noted that `retainAll` test fails and fixed that as well.

**Comment by lukaseder** [comment]
Oops, just saw it, too. Thanks for that additional fix. Travis currently doesn't work for us, as it is still on Java 1.8.0_31, which suffered from lots of compiler bugs.

Yes, please provide a pull request. Looking forward

**Comment by lukaseder** [comment]
Implemented as of #117
