### ISSUE TITLE
Overload methods xyz(Stream, ...) with xyz(Iterable, ...) and xyz(Seq, ...)

### ISSUE THREAD

**Issue by stephenh** [jOOQ/jOOL#106]
I'm basically looking to do:

```
List<E> a = ...
List<E> b = ...
seq(a).concat(b);
```

As basically an alternative to Guava's:

```
FluentIterable.from(a).append(b);
```

I can do:

```
seq(a).concat(b.stream());
```

But every time I see ".stream()", I die a little bit inside.

**Comment by lukaseder** [comment]
That would be convenient indeed. Yet, for consistency reasons, we would have to overload all API to accept both `Stream` and `Iterable`. In fact, we'd have to provide a third overload accepting `Seq`, because `Seq` extends `Stream` and `Iterable`, and adding only the `Iterable` overload would lead to ambiguities.

I'm not 100% sure yet if we should go this way, even if it sounds tempting

**Comment by lukaseder** [comment]
One would wish that `Stream` is `Iterable`, right? Because that would make total sense, right? Guess again :)

Meh, just today, I felt like...
https://twitter.com/lukaseder/status/639802749878697984

I guess I'll just overload, as I totally agree with your pain

**Comment by stephenh** [comment]
> https://twitter.com/lukaseder/status/639802749878697984

Ha, +1 retweeted.

> One would wish that Stream is Iterable, right? Because that would make
> total sense, right? Guess again :)

...son of a... :-)

**Comment by stephenh** [comment]
Thanks!
