### ISSUE TITLE
Add method to create maps from streams with the stream objects as the map values

### ISSUE THREAD

**Issue by sargue** [jOOQ/jOOL#207]
I've been using this construction a lot lately:

```java
Seq<SomeObject> seq = ...;
Map<Integer, SomeObject> objectMap = seq.toMap(SomeObject::getId, Function.identity());
```

And I've think this sugar-addition would be nice for jOOL.

```java
interface Collectable<T> {
    /**
     * Collect the collectable into a {@link Map} with the given keys
     * and the self element as value.
     */
    <K> Map<K, T> toIdentityMap(Function<? super T, ? extends K> keyMapper);
}
```

I can provide a PR. Alternative names to `toIdentityMap` are very welcome. ;-)

**Comment by lukaseder** [comment]
Interesting. Yes, there's room for this feature. Also, the inverse might be useful. For instance, when you have a `Seq<String>`, and you want to create a dictionary from it, like so:

```java
    <V> Map<T, V> toXXXMap(Function<? super T, ? extends V> valueMapper);
```

Now, for the hardest problem: Naming ;)

I don't think that the term "identity" should be used. This is really about keys / values. For consistency reasons, the `to` prefix will be mandatory. Same for the `Map` suffix. `toMapKeys()` and `toMapValues()` aren't perfect, because it's not clear which one is which. E.g. does `Keys` mean that keys are mapped, or that keys are kept? Hmm...

**Comment by amaembo** [comment]
FYI I named such thing simply as [`toMap`](http://amaembo.github.io/streamex/javadoc/one/util/streamex/StreamEx.html#toMap-java.util.function.Function-) providing an overload when value mapper only is specified. With StreamEx, in OP case you still should specify explicitly both mappers. Actually adding `x->x` is not that long, so it's not the big problem.

**Comment by lukaseder** [comment]
Hmm, I'd prefer the keymapper version if an overload is provided. Simply because with convenience overloads, usually, the last argument(s) are the optional ones:

```java
toMap(keyMapper) { return toMap(keyMapper, v -> v); }
toMap(keyMapper, valueMapper)
```

**Comment by sargue** [comment]
@amaembo, I also thought about the `x->x`solution. That would be:

```java
Seq<SomeObject> seq = ...;
Map<Integer, SomeObject> objectMap = seq.toMap(SomeObject::getId, x->x);
```

Or the inverse as commented by @lukaseder 

```java
Seq<String> names = ...;
Map<String,V> dictionary = names.toMap(x->x, Converter::fromString);
```

But, still, jOOL has a lot of these minimum sugar additions and I though it might just be useful. The name is the key (no pun intended) to make it even clearer than a `x->x`.

Options:

1. `toKeysOfMap` / `toValuesOfMap`.
2. `toMapKeys` / `toMapValues`
3. `asKeysOfMap` / `asValuesOfMap`
4. `asMapKeys` / `asMapValues`
5. `mapWithValues` / `mapWithKeys`
6. `mapAsKeys` / `mapAsValues`

All of it horrible, I know. Maybe I prefer the 4th. I know! Consistency! What about the prefix `with` ? It's used on some Java 8 API classes like Java-Time.

**Comment by sargue** [comment]
Well, maybe the overload solution is better. I understand the inverse case but I haven't found it. Instead I have like 10 or 12 cases of the direct case in my current project codebase.

@lukaseder, your call.

**Comment by lukaseder** [comment]
I have thought about all the options myself (including `with` and `as` prefixes), and I'm still not convinced :). The Java-Time API is a bit quirky in my opinion. It mixes enhanced JavaBeans notation (`with` for fluent setters) with non-JavaBeans notation. In my opinion, all those `with` prefixes are unnecessary. I'd prefer `localDate.month(13)` any time over `localDate.withMonth(13)`.

Anyway, what's in a name, eh? :)

After this discussion, I suggest adding the keyMapper only convenience overload, since it is a logical overload in terms of the "last-argument-default" rule, which has served me very well numerous times also in jOOQ:

```
interface Collectable<T> {
    /**
     * ...
     */
    <K> Map<K, T> toMap(Function<? super T, ? extends K> keyMapper);
}
```

In addition to this rationale, it might not be wise to offer a `toMap(valueMapper)` API, because the user should be in control of handling keys (and preventing key conflicts). In other words, keys are more important in maps than values.

If you're still interested in providing the PR, I'd be very happy to merge! :)

**Comment by amaembo** [comment]
@lukaseder yeah, probably `keyMapper` used more frequently. This feature were in the StreamEx from the very beginning (literally, it was added in the [first commit](https://github.com/amaembo/streamex/commit/a44a47b3fb85c7acbb1299773c7cf850b0f362c1#diff-2c98e33e3538c0d9ef6a7438322fe80fR311)!). Probably after more thinking I would use `keyMapper` instead.

**Comment by sargue** [comment]
Ups! Messed the commit message, too late to commit. ;-) But I think the code is ok (it's a keyMapper really). I don't think I can change the commit message... can I? should I?

**Comment by tkroman** [comment]
Isn't this whole thing a composition of `Seq#toMap` and  `Seq#grouped`?

**Comment by lukaseder** [comment]
Noticed the commit message. Never mind :) You could change the commit, but let's leave this as a riddle and bike shedding trap for future readers of commit logs.

@tkroman: No you could compose it, indeed, but this implementation is simpler and faster (grouped is currently not implemented optimally, I suspect). It's really just convenience for `Seq.toMap(mapper, t -> t)`
