### ISSUE TITLE
Bad interaction between skipUntil and splitAtHead

### ISSUE THREAD

**Issue by Master-Killer** [jOOQ/jOOL#236]
Here is an example of a bug when using `splitAtHead` after `skipUntil`.
The bug does not occur when "forcing" the Seq to evaluate after the `skipUntil`.
```java
@Test
public void bugJoolOkWithForcing() {
	final Seq<Integer> integers = Seq.of(1, 2, 3, 4, 5, 6).skipUntil(i -> i == 3);
	System.out.println("integers = " + integers);
	final Tuple2<Optional<Integer>, Seq<Integer>> split = integers.splitAtHead();
	System.out.println("split = " + split);
	Assert.assertEquals(Optional.of(3), split.v1);
	Assert.assertEquals(Arrays.asList(4, 5, 6), split.v2.toList());
}

@Test
public void bugJoolFail() {
	final Tuple2<Optional<Integer>, Seq<Integer>> split = Seq.of(1, 2, 3, 4, 5, 6).skipUntil(i -> i == 3).splitAtHead();
	Assert.assertEquals(Optional.of(3), split.v1);
	Assert.assertEquals(Arrays.asList(4, 5, 6), split.v2.toList());
}
```

**Comment by lukaseder** [comment]
Thank you very much for reporting. 

Hmm, the issue is not strictly related to `splitAtHead()`, but to the fact that `splitAtHead()` operates on `Stream.iterator()`, which triggers a bad call sequence on the internal spliterators. Essentially, the `skipUntil()` (and `skipUntilClosed()`) implementation is wrong.
