### ISSUE TITLE
Release 0.9.15

### ISSUE THREAD

**Issue by murdos** [jOOQ/jOOL#402]
### Expected behavior and actual behavior:

0.9.14 was released back in 2018, it would be nice to release work that has been done since :-)

**Comment by lukaseder** [comment]
Thanks for your message. I was convinced there had been a release since then, but you're right, there hasn't been. And at least 17 things have been improved:
https://github.com/jOOQ/jOOL/issues?q=is%3Aissue+is%3Aclosed+milestone%3A%22Version+0.9.15%22+label%3A%22R%3A+Fixed%22

Will look into this later this week.

**Comment by lukaseder** [comment]
> Will look into this later this week.

Right. "this week." Doing it now 😅

**Comment by lukaseder** [comment]
There you go: https://groups.google.com/g/jooq-user/c/a9dEwS5hkEY
