### ISSUE TITLE
Add Seq.exists(Predicate)

### ISSUE THREAD

**Issue by stephenh** [jOOQ/jOOL#93]
Currently I'm using filter(Predicate).findFirst().isPresent() and .exists(Predicate) would be a little shorter.

**Comment by lukaseder** [comment]
Thanks for the suggestion. Good point!

**Comment by stephenh** [comment]
Erg. Turns out Stream.anyMatch(Predicate) already implements the "exists" logic.

Coming from Scala, I was really expecting/wanting Seq.exists, and just haven't used Streams enough yet to have seen anyMatch. (I actually found it while implementing Seq.exists, and wanting a short-circuit find instead of my original thought of .filter(p).findFirst().isPresent().)

Well, I have the pull request all ready anyway; up to you if you want to merge or not.

**Comment by lukaseder** [comment]
Naming things... hardest problem in software :)

Thanks for the research. I wasn't fluent in `anyMatch()` either, but I suspect that `anyMatch()` will be enough. I'd prefer not to add too many aliases to methods...

**Comment by stephenh** [comment]
I am personally more okay with "fixing Stream's weirdness/incompleteness" extending into adding saner method names :-), but also understood. Thanks!

**Comment by lukaseder** [comment]
I'm personally also in favour with that, but the problem is, that weirdness will inevitably become the new de-facto standard like everything else inside of a `java.util` package (such as `NavigableSet`, which is extremely weird to me). So, jOOλ is about accepting this fate, adding some additional value, and moving on...
